### ISSUE TITLE
题库不够完整

### ISSUE THREAD

**Issue by fyu0h** [kessil/quizXue#1]
题库目前似乎还不够大，很多题目匹配不到

**Comment by kessil** [comment]
已更新题库，计820题。

**Comment by fyu0h** [comment]
现在的超强了，怕是能连答800题

**Comment by ipez** [comment]
> 已更新题库，计820题。

你好，能问下题库怎么获得的吗？还有答案，是反复刷新页面试出来的吗？

**Comment by kessil** [comment]
> 
> 
> > 已更新题库，计820题。
> 
> 你好，能问下题库怎么获得的吗？还有答案，是反复刷新页面试出来的吗？
运行脚本开始挑战答题，通过自动提交百度查询，用统计学方法作答，并将题目和正确的选项保存到数据库中。通过不断的答题增大数据库的题量，提高题库覆盖率。

**Comment by kessil** [comment]
> 
> 
> > 已更新题库，计820题。
> 
> 你好，能问下题库怎么获得的吗？还有答案，是反复刷新页面试出来的吗？

运行脚本开始挑战答题，通过自动提交百度查询，用统计学方法作答，并将题目和正确的选项保存到数据库中。通过不断的答题增大数据库的题量，提高题库覆盖率。

**Comment by ipez** [comment]
了解了，多谢。
