### ISSUE TITLE
出现问题.安卓9.0 UI hierchary dumped to: /sdcard/ui.xml

### ISSUE THREAD

**Issue by shzxm** [kessil/quizXue#11]
![Snipaste_2019-07-15_14-47-34](https://user-images.githubusercontent.com/9905297/61199166-80471180-a70f-11e9-973c-eb6075f1a995.png)
出现问题.安卓9.0

**Comment by shzxm** [comment]
![Snipaste_2019-07-15_14-50-52](https://user-images.githubusercontent.com/9905297/61199289-f8153c00-a70f-11e9-9e40-4c57edcae22b.png)
重新运行后出现另一个问题

**Comment by kessil** [comment]
上传ui.xml看看

**Comment by kessil** [comment]
> 
> 
> ![Snipaste_2019-07-15_14-47-34](https://user-images.githubusercontent.com/9905297/61199166-80471180-a70f-11e9-973c-eb6075f1a995.png)
> 出现问题.安卓9.0

最新提交版本提供了MuMu模拟器的支持，同时也支持自定义xpath规则，建议尝试一下

**Comment by shzxm** [comment]
好的.谢谢~
