### ISSUE TITLE
反馈新增题目

### ISSUE THREAD

**Issue by hyy34** [kessil/quizXue#12]
七人制橄榄球是        橄榄球的一种，与传统的橄榄球相比，场地、规则大致相同，但人数少、比赛节奏较快而且平均得分较高，受到普遍欢迎。
A. 美式: 10
B. 英式: 12
C. 澳式: 3
D. 联盟式: 0
------------------------------------------------------------------------------------------------------------------------
请先在手机提交答案，根据提交结果输入答案！
请输入：b
数据库添加记录成功！

1992年阿尔贝维尔冬奥会，中国运动员        在速度滑冰项目上获得两枚宝贵的银牌，结束了我国在冬奥会上未获奖牌的历史。
A. 杨扬: 1
B. 叶乔波: 6
C. 韩晓鹏: 0
D. 李佳军: 3
------------------------------------------------------------------------------------------------------------------------
请先在手机提交答案，根据提交结果输入答案！
请输入：b
数据库添加记录成功！

高山滑雪起源于欧洲的阿尔卑斯山脉地区，所以又被称为“阿尔卑斯滑雪”。1936年在        举行的第四届冬奥会上被列为比赛项目。
A. 丹麦: 0
B. 德国: 0
C. 捷克: 0
D. 比利时: 0
------------------------------------------------------------------------------------------------------------------------
请先在手机提交答案，根据提交结果输入答案！
请输入：b
数据库添加记录成功！

**Comment by kessil** [comment]
已更新
