### ISSUE TITLE
新增题目反馈

### ISSUE THREAD

**Issue by hyy34** [kessil/quizXue#22]
赛艇运动使用的船艇最初是人们日常的交通工具，被称为“水上巴士”。17世纪的泰晤士河上，船工们经常举行划船比赛。赛艇运动起源于        。
A. 英国: 0
B. 法国: 0
C. 意大利: 0
D. 希腊: 0
------------------------------------------------------------------------------------------------------------------------
请先在手机提交答案，根据提交结果输入答案！
请输入：a（A为正确答案）
数据库添加记录成功！

------------------------------------------------
使用灭火器进行灭火的最佳位置是        。
A. 下风位置: 7
B. 上风或侧风位置: 1
C. 离起火点10米以上位置: 0
------------------------------------------------
请先在手机提交答案，根据提交结果输入答案！
请输入：b（答A错误，提示是B为正确，如果没记错的话）
数据库添加记录成功！

**Comment by hyy34** [comment]
------------------------------------------------------
下列选项中不属于传统知识产权范畴的是        。
A. 使用权: 1
B. 专利权: 1
C. 商标权: 1
D. 著作权: 7
------------------------------------------------------
请先在手机提交答案，根据提交结果输入答案！
请输入：a
数据库添加记录成功！
UI hierchary dumped to: /sdcard/ui.xml
2148 KB/s (21945 bytes in 0.009s)

--------------------------------------------------------------------------------------------------
由田汉作词、聂耳作曲的《义勇军进行曲》，是电影        的主题歌，后成为中华人民共和国国歌。
A. 《聂耳》: 0
B. 《风云儿女》: 3
C. 《中华儿女》: 0
D. 《英雄儿女》: 0
--------------------------------------------------------------------------------------------------
请先在手机提交答案，根据提交结果输入答案！
请输入：b
数据库添加记录成功！
UI hierchary dumped to: /sdcard/ui.xml
2268 KB/s (16369 bytes in 0.007s)

**Comment by kessil** [comment]
反馈新题请到置顶
