### ISSUE TITLE
'gbk' codec can't decode

### ISSUE THREAD

**Issue by K1two2** [kessil/quizXue#30]
![BG7YWL_19-08-07_12-44-44](https://user-images.githubusercontent.com/9145406/62595482-25b96380-b911-11e9-87fa-489d86eabaeb.png)

**Comment by K1two2** [comment]
model.py文件49行也需要采用utf-8编码读取

**Comment by K1two2** [comment]
在MUMU模拟器里面已经测试成功，请问一加6T如何增加XPath。

**Comment by hyy34** [comment]
> 在MUMU模拟器里面已经测试成功，请问一加6T如何增加XPath。

如何解决的这个错误呢？我也是这个错误。手机上。

**Comment by K1two2** [comment]
> > 在MUMU模拟器里面已经测试成功，请问一加6T如何增加的XPath。
> 
> 如何解决的这个错误呢？我也是这个错误。手机上。

由于终端设备差异导致UI布局不尽相同，对于未兼容的设备需要增加对应的XPath

**Comment by hyy34** [comment]
> > > 在MUMU模拟器里面已经测试成功，请问一加6T如何增加的XPath。
> > 
> > 
> > 如何解决的这个错误呢？我也是这个错误。手机上。
> 
> 由于终端设备差异导致UI布局不尽相同，对于未兼容的设备需要增加对应的XPath

由于终端设备差异导致UI布局不尽相同，对于未兼容的设备，欢迎大家在config.ini中增加xpath规则或提交issues

没找到这个config.ini呢。在哪个文件里添加呢？

**Comment by K1two2** [comment]
> > > > 在MUMU模拟器里面已经测试成功，请问一加6T如何增加的XPath。
> > > 
> > > 
> > > 如何解决的这个错误呢？我也是这个错误。手机上。
> > 
> > 
> > 由于终端设备差异导致UI布局不尽相同，对于未兼容的设备需要增加对应的XPath
> 
> 由于终端设备差异导致UI布局不尽相同，对于未兼容的设备，欢迎大家在config.ini中增加xpath规则或提交issues
> 
> 没找到这个config.ini呢。在哪个文件里添加呢？
> 
> C:\venv>python main.py --device huawei_p20
> Traceback (most recent call last):
> File "main.py", line 109, in 
> start(device, count_question, filename, database_uri, delay_seconds, user_agent)
> File "main.py", line 52, in start
> question = Bank.from_xml(device)
> File "C:\venv\model.py", line 49, in from_xml
> cfg.read('./default.ini')
> File "G:\Python\lib\configparser.py", line 696, in read
> self._read(fp, filename)
> File "G:\Python\lib\configparser.py", line 1014, in _read
> for lineno, line in enumerate(fp, start=1):
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1332: illegal multibyte sequence
> 
> C:\venv>python main.py --device mumu
> 默认连接Windows平台MuMu模拟器(测试时版本号:v2.2.7)
> Traceback (most recent call last):
> File "main.py", line 109, in 
> start(device, count_question, filename, database_uri, delay_seconds, user_agent)
> File "main.py", line 52, in start
> question = Bank.from_xml(device)
> File "C:\venv\model.py", line 49, in from_xml
> cfg.read('./default.ini')
> File "G:\Python\lib\configparser.py", line 696, in read
> self._read(fp, filename)
> File "G:\Python\lib\configparser.py", line 1014, in _read
> for lineno, line in enumerate(fp, start=1):
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1332: illegal multibyte sequence
> 
> 错误依旧啊，难道还能识别你用的是不是这个手机？正常应该会出现不准确的情况，但是不应该出错啊。

MUMU模拟器我可以成功使用，模拟器的报错你仔细看我上面的回复。
现在我是手机无法使用，需要增加XPath。

**Comment by hyy34** [comment]
> model.py文件49行也需要采用utf-8编码读取

MUMU模拟器，如何操作解决这个问题的？

**Comment by K1two2** [comment]
> > model.py文件49行也需要采用utf-8编码读取
> 
> MUMU模拟器，如何操作解决这个问题的？

https://github.com/kessil/quizXue/commit/49af0e4073f4efc2edf157905b532ebf02e55c72

**Comment by K1two2** [comment]
这是我手机一加6T的UI布局，APP版本V2.5.0
[ui.txt](https://github.com/kessil/quizXue/files/3475761/ui.txt)

**Comment by K1two2** [comment]
> 这是我手机一加6T的UI布局，APP版本V2.5.0
> [ui.txt](https://github.com/kessil/quizXue/files/3475761/ui.txt)

打算用uiautomatorviewer工具分析，手机没ROOT，uiautomatorviewer一直无法通过ADB连接手机

**Comment by hyy34** [comment]
> 这是我手机一加6T的UI布局，APP版本V2.5.0
> [ui.txt](https://github.com/kessil/quizXue/files/3475761/ui.txt)

这个文件打开后，看的我一头雾水。。

**Comment by K1two2** [comment]
> > 这是我手机一加6T的UI布局，APP版本V2.5.0
> > [ui.txt](https://github.com/kessil/quizXue/files/3475761/ui.txt)
> 
> 这个文件打开后，看的我一头雾水。。

进入挑战答题后用adb shell uiautomator dump /sdcard/ui.xml抓取的布局

**Comment by hyy34** [comment]
需要安装什么东西才能抓取吗？

**Comment by K1two2** [comment]
> 需要安装什么东西才能抓取吗？

百度这段命令你就知道了，“adb shell uiautomator dump /sdcard/ui.xml”

**Comment by K1two2** [comment]
![BG7YWL_19-08-07_23-04-28](https://user-images.githubusercontent.com/9145406/62634099-e23e1400-b967-11e9-873e-838448af9c15.png)

**Comment by kessil** [comment]
刚提交了dev分支，本地测试使用正常
