### ISSUE TITLE
新版所有功能一切正常

### ISSUE THREAD

**Issue by ysymmsj** [kessil/quizXue#33]
每日答题和挑战答题都正常在模拟器中正常运行没有错误。谢谢大神

**Comment by K1two2** [comment]
我这边测试输入法中文乱码，在系统设置里面已经把默认输入法设置为ADBBoardkey。
MuMu模拟器2.2.13.2，ADB 1.0.31，Python 3.7.2，学习强国 2.5.0
![BG7YWL_19-08-08_15-04-44](https://user-images.githubusercontent.com/9145406/62713488-66a79a00-ba2f-11e9-882e-8539fd579776.png)

**Comment by ysymmsj** [comment]
你这个把ADB 1.0.31换成ADB 1.0.40就可以了

**Comment by ysymmsj** [comment]
ADB 1.0.31换成ADB 1.0.40就可以啦

**Comment by ysymmsj** [comment]
ADB 1.0.31换成ADB 1.0.40就可以啦
