### ISSUE TITLE
每日 每周 专项可以使用吗？

### ISSUE THREAD

**Issue by hyy34** [kessil/quizXue#5]
如果每日 每周 专项可以半自动就好了，太浪费时间了。。

还有就是 请问 磨题帮题库 是个什么？

**Comment by kessil** [comment]
> 
> 
> 如果每日 每周 专项可以半自动就好了，太浪费时间了。。
> 
> 还有就是 请问 磨题帮题库 是个什么？

由于这三个练习本来就有答案，而且题目类型多样，目前不考虑实现。磨题帮可用来平时做练习、背题，类似驾考宝典app

**Comment by hyy34** [comment]
> > 如果每日 每周 专项可以半自动就好了，太浪费时间了。。
> > 还有就是 请问 磨题帮题库 是个什么？
> 
> 由于这三个练习本来就有答案，而且题目类型多样，目前不考虑实现。磨题帮可用来平时做练习、背题，类似驾考宝典app

虽然有答案，主要是太浪费时间了，希望能加进去就好了。
还有这几天遇到好几次需要手动输入答案了，而且答案后面有数字的基本就是正确答案，请问出现这个情况的原因是什么？题库里没有吗？但是没有怎么还能提示正确答案呢。

**Comment by kessil** [comment]
> 
> 
> > > 如果每日 每周 专项可以半自动就好了，太浪费时间了。。
> > > 还有就是 请问 磨题帮题库 是个什么？
> > 
> > 
> > 由于这三个练习本来就有答案，而且题目类型多样，目前不考虑实现。磨题帮可用来平时做练习、背题，类似驾考宝典app
> 
> 虽然有答案，主要是太浪费时间了，希望能加进去就好了。
> 还有这几天遇到好几次需要手动输入答案了，而且答案后面有数字的基本就是正确答案，请问出现这个情况的原因是什么？题库里没有吗？但是没有怎么还能提示正确答案呢。
> 然后答题后可能是10几道提就自动退出了，这个是什么原因？还是设置就是如此，因为之前10道题已经够用了。但是现在出另外的积分了，叫“点点通”，需要挑战答对30道题才可以！
> 而且在使用中有时候会重复显示题目，然后继续按照上个题目的答案选择，所以造成失败的情况，其实也可以用，无非就是再多运行一次命令重新答一次，但是也希望能修复。
> 
> 虽然可能存在一些小瑕疵，而且也可能是我操作的问题，但是还是感谢作者的无私奉献。谢谢您。

应该是平台添加了新题，导致很多题需要手动输入，脚本遇到新题只是提交百度查询并打印出结果，同时提醒用户确认答案，不根据统计结果替用户做决定。
脚本设置了随机回答11~20题自动结束，可以自己给run函数的参数num传一个值指定答题数量。

**Comment by hyy34** [comment]
> > > > 如果每日 每周 专项可以半自动就好了，太浪费时间了。。
> > > > 还有就是 请问 磨题帮题库 是个什么？
> > > 
> > > 
> > > 由于这三个练习本来就有答案，而且题目类型多样，目前不考虑实现。磨题帮可用来平时做练习、背题，类似驾考宝典app
> > 
> > 
> > 虽然有答案，主要是太浪费时间了，希望能加进去就好了。
> > 还有这几天遇到好几次需要手动输入答案了，而且答案后面有数字的基本就是正确答案，请问出现这个情况的原因是什么？题库里没有吗？但是没有怎么还能提示正确答案呢。
> > 然后答题后可能是10几道提就自动退出了，这个是什么原因？还是设置就是如此，因为之前10道题已经够用了。但是现在出另外的积分了，叫“点点通”，需要挑战答对30道题才可以！
> > 而且在使用中有时候会重复显示题目，然后继续按照上个题目的答案选择，所以造成失败的情况，其实也可以用，无非就是再多运行一次命令重新答一次，但是也希望能修复。
> > 虽然可能存在一些小瑕疵，而且也可能是我操作的问题，但是还是感谢作者的无私奉献。谢谢您。
> 
> 应该是平台添加了新题，导致很多题需要手动输入，脚本遇到新题只是提交百度查询并打印出结果，同时提醒用户确认答案，不根据统计结果替用户做决定。
> 脚本设置了随机回答11~20题自动结束，可以自己给run函数的参数num传一个值指定答题数量。

明白了，感谢解答。
另外那个修改参数的，可能具体教教傻瓜们如何修改吗？

**Comment by kessil** [comment]
> 
> 
> > > > > 如果每日 每周 专项可以半自动就好了，太浪费时间了。。
> > > > > 还有就是 请问 磨题帮题库 是个什么？
> > > > 
> > > > 
> > > > 由于这三个练习本来就有答案，而且题目类型多样，目前不考虑实现。磨题帮可用来平时做练习、背题，类似驾考宝典app
> > > 
> > > 
> > > 虽然有答案，主要是太浪费时间了，希望能加进去就好了。
> > > 还有这几天遇到好几次需要手动输入答案了，而且答案后面有数字的基本就是正确答案，请问出现这个情况的原因是什么？题库里没有吗？但是没有怎么还能提示正确答案呢。
> > > 然后答题后可能是10几道提就自动退出了，这个是什么原因？还是设置就是如此，因为之前10道题已经够用了。但是现在出另外的积分了，叫“点点通”，需要挑战答对30道题才可以！
> > > 而且在使用中有时候会重复显示题目，然后继续按照上个题目的答案选择，所以造成失败的情况，其实也可以用，无非就是再多运行一次命令重新答一次，但是也希望能修复。
> > > 虽然可能存在一些小瑕疵，而且也可能是我操作的问题，但是还是感谢作者的无私奉献。谢谢您。
> > 
> > 
> > 应该是平台添加了新题，导致很多题需要手动输入，脚本遇到新题只是提交百度查询并打印出结果，同时提醒用户确认答案，不根据统计结果替用户做决定。
> > 脚本设置了随机回答11~20题自动结束，可以自己给run函数的参数num传一个值指定答题数量。
> 
> 明白了，感谢解答。
> 另外那个修改参数的，可能具体教教傻瓜们如何修改吗？

已解决，修复ui.xml为空导致的bug。参数在main.py第83行设置，默认30。

**Comment by hyy34** [comment]
收到，感谢。。测试几天！

**Comment by kessil** [comment]
修复了重复显示题目的问题，将单击屏幕改为长按屏幕50ms
设置答题数默认参数无穷大，运行时传参35.
