### ISSUE TITLE
error: device offline是什么原因！？

### ISSUE THREAD

**Issue by hyy34** [kessil/quizXue#7]
请教下，这个能是什么原因！？
怎么不能上传图片呢？
[https://i.loli.net/2019/07/10/5d254e0de987860867.jpg](https://i.loli.net/2019/07/10/5d254e0de987860867.jpg)

**Comment by asg1101** [comment]
> 请教下，这个能是什么原因！？
> 怎么不能上传图片呢？
> https://i.loli.net/2019/07/10/5d254e0de987860867.jpg

你连接手机并设置成调试模式了吗？

**Comment by kessil** [comment]
> 
> 
> 请教下，这个能是什么原因！？
> 怎么不能上传图片呢？
> https://i.loli.net/2019/07/10/5d254e0de987860867.jpg

检查是否开启USB调试模式，是否最新版本ADB。

**Comment by hyy34** [comment]
> > 请教下，这个能是什么原因！？
> > 怎么不能上传图片呢？
> > https://i.loli.net/2019/07/10/5d254e0de987860867.jpg
> 
> 检查是否开启USB调试模式，是否最新版本ADB。

都开了，可能是连接问题，重新打开几次就好了。
